In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertModel, AdamW, get_linear_schedule_with_warmup
from tqdm import tqdm


/opt/conda/envs/default/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:

# 设置随机种子
seed = 42
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
np.random.seed(seed)

# 加载数据
file_path = '../datasets_FIX2/FIX2_deduplicated_mangoNews_Nums3000p_CategoryMerge_new_undersampled_Example.csv'
# file_path = '../datasets_FIX2/FIX2_deduplicated_mangoNews_Nums3000p_CategoryMerge_new_undersampled.csv'

data = pd.read_csv(file_path,low_memory=False,lineterminator="\n")

# 加载BERT tokenizer和模型
model_name = '../bert-base-multilingual-cased'
tokenizer = BertTokenizer.from_pretrained(model_name)
bert_model = BertModel.from_pretrained(model_name)

# 将模型移动到GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
bert_model.to(device)



In [3]:
# 定义数据集类
class NewsDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=512):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, index):
        text = str(self.texts[index])
        label = self.labels[index]

        encoding = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=self.max_length,
            return_token_type_ids=False,
            padding='max_length',
            return_attention_mask=True,
            return_tensors='pt',
            truncation=True
        )

        return {
            'text': text,
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'label': torch.tensor(label, dtype=torch.long)
        }

# 将孟加拉语类别转换为数字标签
label_map = {label: i for i, label in enumerate(data['category1'].unique())}
labels = data['category1'].map(label_map).tolist()

# 定义LSTM分类器
class LSTMClassifier(nn.Module):
    def __init__(self, bert_model, hidden_size, num_classes, num_layers=1, bidirectional=True, dropout=0.5):
        super(LSTMClassifier, self).__init__()
        self.bert = bert_model
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.bidirectional = bidirectional
        self.dropout = nn.Dropout(dropout)
        self.lstm = nn.LSTM(bert_model.config.hidden_size, hidden_size, num_layers, bidirectional=bidirectional, batch_first=True)
        self.fc = nn.Linear(hidden_size * (2 if bidirectional else 1), num_classes)

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        last_hidden_state = outputs.last_hidden_state
        lstm_output, _ = self.lstm(last_hidden_state)
        lstm_output = self.dropout(lstm_output[:, -1, :])
        logits = self.fc(lstm_output)
        return logits

# 定义训练和评估函数
def train_epoch(model, data_loader, optimizer, scheduler, device):
    model.train()
    total_loss = 0
    progress_bar = tqdm(data_loader, desc='Training', leave=False)
    for batch in progress_bar:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        optimizer.zero_grad()
        logits = model(input_ids, attention_mask)
        print(logits)
        print(logits.shape)
        print(labels)
        print(labels.size())
        
        loss = nn.CrossEntropyLoss()(logits, labels)
        loss.backward()
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()
        progress_bar.set_postfix({'loss': loss.item()})
    return total_loss / len(data_loader)

def evaluate(model, data_loader, device, label_map):
    model.eval()
    predictions = []
    true_labels = []
    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            logits = model(input_ids, attention_mask)
            batch_predictions = torch.argmax(logits, dim=1)
            predictions.extend(batch_predictions.tolist())
            true_labels.extend(labels.tolist())

    label_map_inv = {v: k for k, v in label_map.items()}
    predictions = [label_map_inv[i] for i in predictions]
    true_labels = [label_map_inv[i] for i in true_labels]

    report = classification_report(true_labels, predictions, digits=4)
    return report



In [4]:
# 设置超参数
num_epochs = 2
batch_size =4
learning_rate = 2e-5
hidden_size = 128
num_classes = len(label_map)
kfold = KFold(n_splits=5, shuffle=True, random_state=seed)

# 存储所有fold的性能指标
all_reports = []

# K-Fold交叉验证
for fold, (train_idx, val_idx) in enumerate(kfold.split(data)):
    print(f'Fold {fold + 1}')
    
    train_data = data.iloc[train_idx]
    val_data = data.iloc[val_idx]

    train_texts = train_data['body'].tolist()
    train_labels = train_data['category1'].map(label_map).tolist()
    val_texts = val_data['body'].tolist()
    val_labels = val_data['category1'].map(label_map).tolist()

    train_dataset = NewsDataset(train_texts, train_labels, tokenizer)
    val_dataset = NewsDataset(val_texts, val_labels, tokenizer)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)

    model = LSTMClassifier(bert_model, hidden_size, num_classes)
    model.to(device)

    optimizer = AdamW(model.parameters(), lr=learning_rate)
    total_steps = len(train_loader) * num_epochs
    scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)

    best_val_loss = float('inf')
    for epoch in range(num_epochs):
        train_loss = train_epoch(model, train_loader, optimizer, scheduler, device)
        val_report = evaluate(model, val_loader, device, label_map)

        print(f'Epoch {epoch + 1}/{num_epochs}')
        print(f'Train Loss: {train_loss:.4f}')
        print('Validation Report:')
        print(val_report)

        val_loss = 1 - float(val_report.split('\n')[-2].split()[-2])  # 提取验证集损失
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), f'besta_model_fold_{fold + 1}.pth')

    # 在每个fold结束后,评估最佳模型在验证集上的性能
    best_model = LSTMClassifier(bert_model, hidden_size, num_classes)
    best_model.load_state_dict(torch.load(f'besta_model_fold_{fold + 1}.pth'))
    best_model.to(device)
    val_report = evaluate(best_model, val_loader, device, label_map)
    all_reports.append(val_report)

    print(f'Fold {fold + 1} Best Validation Report:')
    print(val_report)
    print()
    



Fold 1


/opt/conda/envs/default/lib/python3.8/site-packages/transformers/optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Training:   0%|          | 0/200 [00:00<?, ?it/s]

tensor([[-0.3022,  0.0833,  0.0065,  0.1480,  0.0466,  0.0124,  0.4299,  0.2868,
         -0.1390],
        [-0.2332,  0.0940,  0.0132,  0.3554,  0.2112, -0.1020,  0.2920,  0.1797,
         -0.0688],
        [-0.0917,  0.0694,  0.0541,  0.1740,  0.0213, -0.1568,  0.1943,  0.0707,
          0.0640],
        [-0.2144, -0.0488,  0.0340,  0.1591,  0.2035, -0.1157,  0.0993,  0.0322,
          0.0656]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([2, 3, 8, 1], device='cuda:0')
torch.Size([4])


Training:   1%|          | 2/200 [00:00<01:24,  2.33it/s, loss=2.21]

tensor([[-0.2687,  0.1010,  0.3368,  0.1046, -0.0022,  0.0440,  0.0258,  0.0593,
          0.0848],
        [-0.1179,  0.1243,  0.2572, -0.1599,  0.1176, -0.0150, -0.0968, -0.0684,
          0.3300],
        [-0.0784,  0.2030,  0.2357,  0.0205, -0.2039, -0.0344,  0.1700,  0.0121,
          0.1421],
        [-0.1622,  0.1535,  0.2404, -0.1118,  0.1789,  0.0450, -0.0150, -0.0622,
          0.0926]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([1, 6, 1, 6], device='cuda:0')
torch.Size([4])


Training:   2%|▏         | 3/200 [00:01<01:12,  2.73it/s, loss=2.28]

tensor([[-0.2286,  0.2019,  0.2686,  0.0574, -0.1208,  0.0037,  0.1854,  0.0259,
          0.2144],
        [-0.1474,  0.3577,  0.3038,  0.0123,  0.1107,  0.2241,  0.0065, -0.0138,
          0.0915],
        [-0.3490,  0.2145,  0.2209,  0.1633,  0.0556, -0.2043,  0.3013,  0.0208,
          0.0973],
        [-0.1491,  0.2287,  0.4997,  0.0944, -0.0322,  0.0188, -0.0251,  0.0451,
          0.1994]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([1, 5, 0, 6], device='cuda:0')
torch.Size([4])


Training:   2%|▏         | 4/200 [00:01<00:58,  3.33it/s, loss=2.23]

tensor([[-0.2380,  0.4346,  0.2587, -0.1027, -0.0122,  0.1008,  0.1194, -0.0763,
          0.2470],
        [-0.1151,  0.1880,  0.1389,  0.2970,  0.1727, -0.1997,  0.3606,  0.0591,
         -0.0015],
        [-0.5138,  0.6042,  0.3456,  0.2407, -0.1979,  0.0239,  0.0901, -0.2281,
          0.2427],
        [-0.0989,  0.2548,  0.3308, -0.0437, -0.0569,  0.0722,  0.1141, -0.1284,
          0.1068]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([4, 2, 6, 5], device='cuda:0')
torch.Size([4])


Training:   2%|▎         | 5/200 [00:01<00:59,  3.29it/s, loss=2.26]

tensor([[-0.2054,  0.2848,  0.3025, -0.0130, -0.0216, -0.1902,  0.0162, -0.0777,
          0.1812],
        [-0.0150,  0.2654,  0.0559,  0.0792,  0.0850, -0.0616,  0.2383, -0.0532,
          0.1975],
        [-0.1311,  0.3063, -0.0088,  0.0575,  0.1229,  0.0144,  0.2228, -0.1931,
          0.2794],
        [-0.3107,  0.3073,  0.3583, -0.2052, -0.1578, -0.0717,  0.0809, -0.0694,
          0.0727]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([4, 5, 1, 3], device='cuda:0')
torch.Size([4])


Training:   3%|▎         | 6/200 [00:02<00:57,  3.35it/s, loss=2.08]

tensor([[-0.0833,  0.4157,  0.0284,  0.0226,  0.0192, -0.0251,  0.1990, -0.0438,
          0.0862],
        [-0.1246,  0.5749,  0.1940, -0.1322, -0.2166, -0.0891,  0.2305, -0.1457,
         -0.1612],
        [-0.1397,  0.3813, -0.0458,  0.0700,  0.0491,  0.1311,  0.2774, -0.1228,
          0.2213],
        [-0.0088,  0.4093,  0.1601,  0.2451,  0.1524, -0.0556,  0.2062, -0.2057,
          0.1380]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([7, 1, 5, 4], device='cuda:0')
torch.Size([4])


Training:   4%|▎         | 7/200 [00:02<00:51,  3.78it/s, loss=2.19]

tensor([[-0.3521,  0.5293,  0.3024, -0.0974, -0.0960,  0.0442,  0.2811, -0.2341,
          0.0454],
        [-0.0665,  0.3435,  0.1568, -0.0849, -0.2197, -0.0277,  0.3396, -0.1481,
          0.0390],
        [-0.3162,  0.4119,  0.2874,  0.0932,  0.0056,  0.1952,  0.2249, -0.1801,
          0.0741],
        [-0.2278,  0.3950,  0.1455,  0.0036,  0.0344,  0.1308,  0.2193,  0.0081,
         -0.1309]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([5, 3, 2, 5], device='cuda:0')
torch.Size([4])


Training:   4%|▍         | 8/200 [00:02<00:54,  3.51it/s, loss=2.11]

tensor([[-0.2588,  0.6145,  0.1416,  0.1329, -0.0047,  0.1537,  0.1461,  0.0084,
         -0.1365],
        [-0.2578,  0.5327,  0.0751, -0.1927, -0.0879,  0.0695,  0.1291, -0.1837,
         -0.1107],
        [-0.1657,  0.5251,  0.2247, -0.0010,  0.0619,  0.2417,  0.2548, -0.2410,
          0.1566],
        [-0.1229,  0.3582,  0.0125,  0.2310, -0.0045,  0.0852,  0.3606,  0.0138,
          0.0414]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([1, 3, 5, 5], device='cuda:0')
torch.Size([4])


Training:   4%|▍         | 9/200 [00:02<00:55,  3.43it/s, loss=2.12]

tensor([[-0.1568,  0.5515,  0.0927, -0.1358, -0.1779,  0.2404,  0.0581, -0.2677,
         -0.0589],
        [-0.1156,  0.4762,  0.1693, -0.1553, -0.1022,  0.0706,  0.0160, -0.1276,
          0.0773],
        [-0.3198,  0.5965,  0.2838,  0.0065,  0.0643,  0.1926,  0.1077, -0.0839,
          0.0312],
        [-0.2653,  0.4384,  0.0347,  0.0183,  0.0614,  0.1772,  0.2749, -0.0702,
          0.1560]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([2, 1, 7, 8], device='cuda:0')
torch.Size([4])


Training:   5%|▌         | 10/200 [00:03<00:50,  3.75it/s, loss=2.17]

tensor([[-0.2918,  0.4906,  0.0758,  0.0894, -0.1356,  0.4015,  0.1698, -0.0931,
          0.1828],
        [-0.1186,  0.6541,  0.2175, -0.0094, -0.0836, -0.0531,  0.2820, -0.1058,
          0.0307],
        [-0.2684,  0.6489,  0.1535, -0.0321, -0.2982,  0.4449,  0.0524,  0.0291,
         -0.0883],
        [-0.1267,  0.2733, -0.0661,  0.2930,  0.0181,  0.1761,  0.3565, -0.0956,
         -0.0351]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([3, 2, 3, 3], device='cuda:0')
torch.Size([4])


Training:   6%|▌         | 11/200 [00:03<00:54,  3.50it/s, loss=2.06]

tensor([[-0.2578,  0.3469,  0.1035, -0.0457,  0.0708,  0.1950,  0.1549, -0.1766,
          0.1610],
        [-0.3186,  0.6412,  0.2105, -0.1525, -0.1805,  0.1875,  0.0190, -0.0213,
         -0.0660],
        [-0.1485,  0.4962, -0.0175,  0.1001, -0.1821,  0.2045,  0.3444, -0.1124,
         -0.1204],
        [-0.1466,  0.2048,  0.1587, -0.0117,  0.1133,  0.0967,  0.2760, -0.1310,
          0.0364]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([4, 1, 2, 2], device='cuda:0')
torch.Size([4])


Training:   6%|▌         | 12/200 [00:03<00:53,  3.53it/s, loss=2.38]

tensor([[-0.2625,  0.6281,  0.0587,  0.1010, -0.4542,  0.2234,  0.1844, -0.3316,
          0.0317],
        [-0.2302,  0.3120,  0.0009,  0.0500, -0.0787,  0.1147, -0.0076, -0.1297,
         -0.0503],
        [-0.2465,  0.5599,  0.0722,  0.0747, -0.1071,  0.3565,  0.0248, -0.0236,
         -0.1089],
        [-0.1297,  0.5726,  0.0674, -0.0417,  0.0574,  0.2077,  0.2189,  0.0056,
         -0.0384]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([6, 0, 0, 0], device='cuda:0')
torch.Size([4])


Training:   6%|▋         | 13/200 [00:03<00:46,  4.00it/s, loss=1.98]

tensor([[-0.0594,  0.6077,  0.2570,  0.1881, -0.2054,  0.3060,  0.0954, -0.2318,
          0.0077],
        [-0.2946,  0.4427,  0.2310, -0.0410, -0.0397,  0.1853,  0.1558, -0.2539,
         -0.2021],
        [-0.3950,  0.6884,  0.1577, -0.0104, -0.2228, -0.0323, -0.1365, -0.3360,
         -0.1243],
        [-0.3430,  0.4128,  0.1164, -0.0662,  0.0960,  0.1341,  0.1337, -0.1844,
          0.0861]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([1, 6, 1, 0], device='cuda:0')
torch.Size([4])


Training:   7%|▋         | 14/200 [00:04<00:49,  3.72it/s, loss=2]   

tensor([[-0.0518,  0.2803,  0.1355,  0.0638, -0.2072,  0.1144, -0.0365, -0.1716,
         -0.1923],
        [-0.3280,  0.4375,  0.0431,  0.0720, -0.3322,  0.2903,  0.2488, -0.2121,
         -0.1232],
        [-0.1481,  0.4140,  0.0762,  0.2353,  0.0520,  0.0563,  0.2969, -0.0537,
          0.0757],
        [-0.0747,  0.5197,  0.1339,  0.3300, -0.0035,  0.1599,  0.3141, -0.1548,
         -0.1774]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([1, 1, 3, 5], device='cuda:0')
torch.Size([4])


Training:   8%|▊         | 15/200 [00:04<00:52,  3.52it/s, loss=2.23]

tensor([[-0.3062,  0.5322, -0.1378,  0.1024, -0.1127,  0.1146,  0.0540, -0.1489,
         -0.1714],
        [-0.1680,  0.5568, -0.0142,  0.0042, -0.0277,  0.2114,  0.2458, -0.1116,
          0.0825],
        [-0.1050,  0.3927,  0.0715, -0.0378, -0.0530,  0.2183,  0.0212, -0.0366,
         -0.0421],
        [-0.3098,  0.5896,  0.3647,  0.1856, -0.3830,  0.2422,  0.3062, -0.2146,
         -0.0715]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([6, 4, 3, 3], device='cuda:0')
torch.Size([4])


Training:   8%|▊         | 16/200 [00:04<00:46,  3.95it/s, loss=2.14]

tensor([[-0.1569,  0.3638,  0.0133, -0.0971,  0.0168,  0.3177,  0.0522,  0.0483,
          0.0514],
        [-0.2736,  0.5894,  0.2203,  0.1403, -0.2083,  0.2270,  0.1125, -0.3228,
         -0.0351],
        [-0.1209,  0.2447,  0.0261,  0.3206, -0.1683, -0.0916,  0.2935, -0.3264,
         -0.2111],
        [-0.3982,  0.7063,  0.1766,  0.0633, -0.3438,  0.3040,  0.2869, -0.2735,
         -0.0540]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([5, 1, 7, 8], device='cuda:0')
torch.Size([4])


Training:   8%|▊         | 17/200 [00:04<00:50,  3.65it/s, loss=2.31]

tensor([[ 0.0643,  0.8043,  0.1632,  0.3754, -0.3566,  0.4638,  0.1574,  0.0311,
         -0.1391],
        [-0.1575,  0.4763,  0.1774,  0.2659, -0.2215,  0.4101,  0.1701, -0.2461,
         -0.1117],
        [-0.2635,  0.8364,  0.2838,  0.2292, -0.3670,  0.2296,  0.0699, -0.2177,
         -0.0720],
        [-0.2916,  0.4238,  0.3105,  0.0343, -0.4097,  0.0597,  0.2250, -0.2320,
         -0.1803]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([0, 6, 6, 7], device='cuda:0')
torch.Size([4])


Training:   9%|▉         | 18/200 [00:05<00:51,  3.56it/s, loss=2.14]

tensor([[-0.4510,  0.6912,  0.3422,  0.0212, -0.3068,  0.2498,  0.1062, -0.3254,
         -0.1890],
        [-0.1542,  0.4360,  0.1310,  0.0566,  0.0412,  0.2739,  0.3082, -0.1216,
          0.0404],
        [-0.1382,  0.2076,  0.0457, -0.0652, -0.0047,  0.3000,  0.1458, -0.1220,
         -0.0087],
        [-0.3349,  0.7580,  0.2019,  0.1891, -0.2097,  0.6321, -0.0194, -0.0595,
          0.0425]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([4, 6, 2, 5], device='cuda:0')
torch.Size([4])


Training:  10%|▉         | 19/200 [00:05<00:44,  4.11it/s, loss=2.26]

tensor([[-0.3602,  0.3585,  0.1841, -0.0130, -0.2256,  0.0487,  0.1710, -0.2745,
         -0.0035],
        [-0.1484,  0.7172,  0.1484,  0.2972, -0.2441,  0.2913,  0.3247, -0.1673,
         -0.3037],
        [-0.1658,  0.3051,  0.0714,  0.2631, -0.2827,  0.2755,  0.2113, -0.1202,
         -0.2443],
        [-0.0643,  0.5013,  0.0598,  0.2971, -0.0166,  0.4549,  0.1943, -0.0339,
         -0.0042]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([8, 3, 7, 4], device='cuda:0')
torch.Size([4])
tensor([[-0.2302,  0.2968,  0.0109,  0.0689,  0.2242,  0.0865,  0.2129, -0.1457,
          0.0824],
        [-0.4363,  0.3731,  0.0483,  0.1068,  0.0414,  0.1624,  0.2452, -0.2163,
          0.0848],
        [-0.2452,  0.6634,  0.2592,  0.0864, -0.0946,  0.2095,  0.4221, -0.1153,
         -0.0099],
        [ 0.0015,  0.5014,  0.3063,  0.1471, -0.2404,  0.5820,  0.0873, -0.3201,
         -0.0947]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([6, 4, 7, 8],

Training:  10%|█         | 21/200 [00:06<00:49,  3.59it/s, loss=2.38]

tensor([[-0.2578,  0.4973,  0.2203,  0.3343, -0.2428,  0.1570,  0.1546, -0.0083,
         -0.2099],
        [-0.1109,  0.3372,  0.0208,  0.2043, -0.1945,  0.3846,  0.1782, -0.0648,
         -0.1484],
        [-0.0906,  0.7579,  0.1916,  0.2716, -0.2421,  0.4335,  0.3112, -0.2567,
          0.0317],
        [-0.2120,  0.5395,  0.2111,  0.2034, -0.4685,  0.5433,  0.2333, -0.0853,
         -0.0630]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 9])
tensor([3, 7, 7, 0], device='cuda:0')
torch.Size([4])


KeyboardInterrupt: 

In [ ]:
# 计算并打印所有fold的平均性能
print('Average Performance Across All Folds:')
avg_report = pd.DataFrame([report.split() for report in all_reports]).mean(axis=0)
avg_report = '\n'.join([('{:<10}'.format(col) + '{:.4f}'.format(val)) for col, val in zip(avg_report.index, avg_report.values)])
print(avg_report)

In [9]:
print(all_reports)

['              precision    recall  f1-score   support\n\n    অন্যান্য     1.0000    0.7222    0.8387        18\n    অর্থনীতি     0.9630    0.8966    0.9286        29\n         আইন     0.8667    0.9630    0.9123        27\n    খেলাধুলা     0.9583    1.0000    0.9787        23\n     বিজ্ঞান     0.9200    0.9583    0.9388        24\n      বিনোদন     0.9545    1.0000    0.9767        21\n     রাজনীতি     0.9615    1.0000    0.9804        25\n  লাইফস্টাইল     0.9412    0.9412    0.9412        17\n      শিক্ষা     0.8750    0.8750    0.8750        16\n\n    accuracy                         0.9350       200\n   macro avg     0.9378    0.9285    0.9300       200\nweighted avg     0.9377    0.9350    0.9336       200\n', '              precision    recall  f1-score   support\n\n    অন্যান্য     1.0000    0.8696    0.9302        23\n    অর্থনীতি     1.0000    0.9000    0.9474        20\n         আইন     1.0000    1.0000    1.0000        22\n    খেলাধুলা     1.0000    1.0000    1.0000        25

In [11]:
# 计算并打印所有fold的平均性能
print('Average Performance Across All Folds:')
all_lines = [report.split('\n') for report in all_reports]
header = all_lines[0][0] + '\t' + '\t'.join([line.strip() for line in all_lines[0][-4:]])

values = []
for report in all_reports:
    lines = report.split('\n')
    cls_lines = lines[1:-5]
    cls_values = []
    for line in cls_lines:
        parts = line.split()
        if len(parts) >= 5:
            cls_values.append([float(val) if val != 'nan' else 0.0 for val in parts[1:-1]])
    values.append(cls_values)

avg_values = np.mean(values, axis=0)
cls_report = '\n'.join([f'{cls}\t{prec:.4f}\t{rec:.4f}\t{f1:.4f}\t{sup:.0f}' for cls, (prec, rec, f1, sup) in zip(label_map.keys(), avg_values)])

avg_acc = np.mean([float(line.split()[-2]) for report in all_reports for line in report.split('\n') if 'accuracy' in line])
avg_macro = np.mean([float(line.split()[-2]) for report in all_reports for line in report.split('\n') if 'macro avg' in line])
avg_weighted = np.mean([float(line.split()[-2]) for report in all_reports for line in report.split('\n') if 'weighted avg' in line])

avg_report = header + '\n' + cls_report + '\n' + f"accuracy\t{avg_acc:.4f}\nmacro avg\t{avg_macro:.4f}\nweighted avg\t{avg_weighted:.4f}"
print(avg_report)

Average Performance Across All Folds:


ValueError: not enough values to unpack (expected 4, got 3)